### ISSUE TITLE
opengl issue

### ISSUE THREAD

**Issue by XiaoKangW** [vguzov/hps_dataset_scripts#1]
Hi, Vladimir.

Great work. i want to try render the result of sample,and i use your provided dependence,  but there are some opengl issue couldn't be addressed. could you can help me?

Thanks!

The problem as follow:

libEGL warning: DRI2: failed to create dri screen
libEGL warning: Not allowed to force software rendering when API explicitly selects a hardware device.
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "render_visual_localization.py", line 60, in <module>
    if not ctx.initialize(*resolution):
  File "/home/wxk/Project/HPS/hps/dataset/hps_dataset_scripts/egl_renderer/libegl/context.py", line 42, in initialize
    if not self.initialize_on_device(device, width, height):
  File "/home/wxk/Project/HPS/hps/dataset/hps_dataset_scripts/egl_renderer/libegl/context.py", line 62, in initialize_on_device
    if not egl.eglInitialize(egl_dpy, pointer(major), pointer(minor)):
  File "/home/wxk/.conda/envs/hps_env/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/wxk/.conda/envs/hps_env/lib/python3.6/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f05894776a8>,
		<OpenGL.raw.EGL._types.LP_c_int object at 0x7f058948e6a8>,
		<OpenGL.raw.EGL._types.LP_c_int object at 0x7f058948e730>,
	),
	result = 0
)

**Comment by vguzov** [comment]
Hello Xiao, 
Thanks a lot!
I’ve never seen an error like this, but it seems like something is wrong with EGL setup. Could you tell me please which OS and GPU are you using?

**Comment by XiaoKangW** [comment]
Thanks for your reply!

My os is ubuntu 18.04 and GPU is RTX 3090.

**Comment by vguzov** [comment]
I see, this should work fine on your hardware... Are you using Docker or VM? Seems like such issues are mostly happening there. If not, does your nvidia drivers and nvidia-smi work properly?
